e_commerce/common/urls.py
from django.urls import path
from . import views

app_name="common"
urlpatterns=[
    path('customer_login',views.customer_login,name='custlo'),
    path('customer_reg',views.customer_reg,name='custreg'),
    path('',views.project_home1,name='prohome'),
    path('seller_login',views.seller_login,name='sellerlog'),
    path('seller_reg',views.seller_reg,name='sellerreg'),
    path('check_email',views.check_email,name='check_email'),
]    

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('reseller/', include('reseller.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('student/', include('restapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

e_commerce/common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    Customer_name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    phone = models.BigIntegerField()
    gender = models.CharField(max_length=10)
    address = models.CharField(max_length=100, default= '')
    password = models.CharField(max_length=50)

class Seller(models.Model):
    seller_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.BigIntegerField()
    company_name = models.CharField(max_length=50)
    acc_holder_name = models.CharField(max_length=50)
    ifsc = models.CharField(max_length=25, default= '')
    branch = models.CharField(max_length=50)
    acc_no = models.BigIntegerField()
    upload = models.ImageField(upload_to='seller/', default= '')
    user_name = models.CharField(max_length=150, default= '')
    password = models.CharField(max_length=50, default='')
    

e_commerce/common/views.py
from django.shortcuts import render,redirect
from.models import Customer, Seller
import random
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse
from .decorator import auth_customer

# Create your views here.

def customer_login(request):
    msg = ''
    if request.method == 'POST':
        username = request.POST['user_name']
        c_password = request.POST['password']

        try:
            customer = Customer.objects.get(email = username, password = c_password )
            request.session['customer'] = customer.id
            return redirect('customer:cushome')
        except :
            msg = 'incorrect username or password'

    return render(request, 'commontemplates/customer_login.html',{'message':msg})


def customer_reg(request):
    if request.method == 'POST' :   # when submit button clicked
        c_name = request.POST['Name']   # to get textbox data
        c_email = request.POST['email']
        c_phone = request.POST['phone']
        c_gender = request.POST['gender']
        c_address = request.POST['address']
        c_password = request.POST['password']

        # in ORM, if we want to insert a date in table
        # 1.create an object of model class, here model class is Customer

        new_customer = Customer(Customer_name = c_name, email = c_email, phone = c_phone, gender = c_gender,
        address = c_address, password = c_password)
        #call save() method
        new_customer.save()     

    return render(request, 'commontemplates/customer_reg.html')

@auth_customer
def project_home1(request):
    return render(request, 'commontemplates/project_home1.html')


def seller_login(request):
    msg = ''
    if request.method == 'POST' :
        s_name = request.POST['username']
        s_password = request.POST['password']

      # when we use get() to fetch data, we must use try except
      # if the data is not found in the table, exception will be raised

        try:
            seller = Seller.objects.get(user_name = s_name, password = s_password)
            request.session['seller'] = seller.id
            return redirect('reseller:rehome')
        except:
            msg = 'incorrect username & password'   
        
    return render(request, 'commontemplates/seller_login.html',{'message':msg})


def seller_reg(request):
    if request.method == 'POST' :
        s_name = request.POST['seller_name']
        s_email = request.POST['email']
        s_phone = request.POST['phone']
        s_cname = request.POST['company_name']
        s_hname = request.POST['holder_name']
        s_ifsc = request.POST['ifsc']
        s_branch = request.POST['branch']
        s_accno = request.POST['acc_no']
        s_photo = request.FILES["imgg"]

        user_name = random.randint(1111,9999)
        password = 'sel-' + str(user_name) + s_cname # result = sel-5451-john
        new_seller = Seller(seller_name = s_name, email = s_email, phone = s_phone, 
        company_name = s_cname, acc_holder_name = s_hname, ifsc = s_ifsc, branch = s_branch, acc_no = s_accno,
        upload = s_photo, password = password, user_name = user_name)

        new_seller.save()

        message = 'Hi your user name is' + str(user_name) + 'and password is ' + password

        # send_mail function used to send mail through our application
        # 1st arguement -> subject
        # 2st arguement -> message
        # 3st arguement -> from email
        # 4st arguement -> recipent list , here recipent list should be in an array format


        send_mail('username and password',  
        message,
        settings.EMAIL_HOST_USER,
        [s_email])
    

    return render(request, 'commontemplates/seller_reg.html')


def check_email(request):
    email = request.POST['email']

    exist = Customer.objects.filter(email = email).exists()

    return JsonResponse({'status' : exist})   

e_commerce/common/templates/commontemplates/customer_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/cuslog.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color:black">
    <form class="div1" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
       {{message}}
        <h3 id="log">Log In</h3>
        <div class="mb-3">
          <label  class="form-label">Username:</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="user_name">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password:</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
          <button type="submit" class="btn btn-dark">login</button>
        <div>
            didn't : <a href="{% url 'common:custreg' %}" id="signup">Signup</a>
          </div>
      </form>

</body>
</html>

e_commerce/common/templates/commontemplates/customer_reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/cusregn.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
</head>

<body style="background-color:black">

  <section class="div1">
    <form method="POST">
      {% csrf_token %}

      <h3 id="sign">SignUp</h3> <br>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Name </label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="inputEmail3" name="Name">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Email </label>
        <div class="col-sm-10">
          <input type="email" class="form-control" name="email" id="cust_email">
          <span id="err" style="color: red;"></span>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Phone </label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="phone">
        </div>
      </div>
  
      <label for="">Gender</label>
      <div class="form-check" id="gen">
        <input class="form-check-input" type="radio" name="gender"  value="M">
        <label class="form-check-label" for="flexRadioDefault1">Male</label> 
      </div>
      <div class="form-check" id="gen">
        <input class="form-check-input" type="radio" name="gender"  value="F">
        <label class="form-check-label" for="flexRadioDefault1">Female</label> 
      </div>

      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Address</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="address">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" name="password">
        </div>
        <br><br><br>
        <div class="mb-3">
          <button type="submit" class="btn btn-dark" id="button">SignUp</button>
        </div>
      </div>
      
    </form>
  </section>

  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
  <script>
    $('#cust_email').change(function(){
      $.ajaxSetup({
            headers: {
              "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })

      $.ajax({
        url : "{% url 'common:check_email' %}",
        data : {
          'email' : $(this).val()
        },
        type : 'POST',

        success : function(response){
          if (response.status == true){
            $('#err').html('Email Already Exists')
            document.querySelector('#button').disable = true;
          }
          else {
            $('#err').html('')
          }
          
        }
      })


    })
  </script>

</body>

</html>

e_commerce/common/templates/commontemplates/project_home1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/prohome2.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</head>
<body>
  <section class="div">
     <div class="div1">E-Commerce</div>
     <div class="d-grid gap-1 d-md-flex justify-content-md-center" id="div2">
          <a href="{% url 'common:custlo' %}" id="div3"><button class="btn btn-outline-dark me-md-2" type="button" >Customer</button></a>
          <a href="{% url 'common:sellerlog' %}" id="div3"><button class="btn btn-outline-dark me-md-2" type="button" >Reseller</button></a>
     </div>
 </section>
</body>
</html>

e_commerce/common/templates/commontemplates/seller_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/sellog.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color:black">
    <form class="div1" method="POST">
      {% csrf_token %}
     

        <h3 id="log">Log In</h3>
        {{message}}
        <div class="mb-3">
          <label  class="form-label">Username:</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password:</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
         <a href=""><button type="submit" class="btn btn-dark">login</button></a>
        <div>
            didn't : <a href="{% url 'common:sellerreg' %}" id="sign">Signup</a>
          </div>
      </form>

</body>
</html>

e_commerce/common/templates/commontemplates/seller_reg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/sellregg.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
</head>

<body>

  <body style="background-color: black; ">
    <section class="div1">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <h3 id="sign">SignUp</h3> <br>
        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">Seller Name </label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputEmail3" name="seller_name">
          </div>
        </div>
        <div class="row mb-3">
          <label class="col-sm-2 col-form-label">Email </label>
          <div class="col-sm-10">
            <input type="email" class="form-control" name="email">
          </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Phone </label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="phone">
            </div>
        </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Company Name </label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="company_name">
            </div>
          </div>
          <div class="row mb-3">
              <label class="col-sm-2 col-form-label">Acc holder Name</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="holder_name">
              </div>
          </div>
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label">ifsc no.</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="ifsc">
              </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Branch</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="branch">
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Acc no.</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="acc_no">
                </div>          
          </div>
            <div class="row mb-3">    
                  <label class="col-sm-2 col-form-label">File Upload</label>
                  <div class="col-sm-10">
                    <input type="file" class="form-control" name="imgg">
                  </div>
                  <br><br><br>
                  <div class="mb-3">
                    <button type="submit" class="btn btn-dark">SignUp</button>
                  </div>
            </div>
      </form>
    </section>
  </body>

</html>