e_commerce/common/urls.py
from django.urls import path
from . import views

app_name="common"
urlpatterns=[
    path('customer_login',views.customer_login,name='custlo'),
    path('customer_reg',views.customer_reg,name='custreg'),
    path('',views.project_home1,name='prohome'),
    path('seller_login',views.seller_login,name='sellerlog'),
    path('seller_reg',views.seller_reg,name='sellerreg'),
    path('check_email',views.check_email,name='check_email'),
]    

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('reseller/', include('reseller.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('student/', include('restapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

e_commerce/reseller/urls.py
from django.urls import path
from . import views

app_name="reseller"
urlpatterns=[
    path('add_product',views.add_product,name='addpro'),
    path('change_password',views.change_password,name='chngpass'),
    path('home',views.home,name='rehome'),
    path('order_history',views.order_history,name='ordrhstry'),
    path('product_catalouge',views.product_catalouge,name='procata'),
    path('profile',views.profile,name='profile'),
    path('recent_order',views.recent_order,name='recntordr'),
    path('update_stock',views.update_stock,name='upstck'),
]

e_commerce/reseller/models.py
from django.db import models
from common.models import Seller

# Create your models here.

class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete = models.CASCADE)
    p_name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    p_no = models.BigIntegerField()
    upload = models.ImageField(upload_to='product/', default= '')
    price =   models.FloatField()
    stock = models.ImageField()

e_commerce/reseller/views.py
from django.shortcuts import render
from.models import Product , Seller



# Create your views here.

def add_product(request):

    msg = ''
    if request.method == 'POST':
        pro_name = request.POST['product_name']
        pro_description = request.POST['description']
        pro_no = request.POST['product_no']
        pro_photo = request.FILES['upload']
        pro_price = request.POST['price']
        pro_stock = request.POST['stock']

        new_product = Product(p_name = pro_name, description = pro_description, p_no = pro_no, upload = pro_photo,
        price = pro_price, stock = pro_stock, seller_id = request.session['seller'])    

        new_product.save()

        msg = 'Item added successfully'


    return render(request, 'resellertemplates/add_product.html', {'message' : msg})

def change_password(request):
    msg = ''
    if request.method == 'POST':

        current_pass = request.POST['curpass']
        new_pass = request.POST['newpass']
        confirm_pass = request.POST['conpass']

        seller = Seller.objects.get(id = request.session['seller']) 
        if seller.password == current_pass:

            if new_pass == confirm_pass:
                Seller.objects.filter(id = request.session['seller']).update(password = new_pass)
                msg = 'Password Change Successfully'
            else:
                msg = 'Password Doesnot Match' 

        else:
            msg = 'Incorrect Password'          


    return render(request, 'resellertemplates/change_password.html',{'message':msg})

def home(request):
    return render(request, 'resellertemplates/home.html')

def order_history(request):
    return render(request, 'resellertemplates/order_history.html')

def product_catalouge(request):
    seller_data = Seller.objects.get(id = request.session['seller'])
    seller_products = Product.objects.filter(seller = request.session['seller'])
   
    return render(request, 'resellertemplates/product_catalouge.html',{'products': seller_products})

def profile(request):
    return render(request, 'resellertemplates/profile.html')

def recent_order(request):
    return render(request, 'resellertemplates/recent_order.html')

def update_stock(request):
    return render(request, 'resellertemplates/update_stock.html')

e_commerce/reseller/templates/resellertemplates/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/addpro.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
</head>

<body style="background-color: black;">
  <section class="div1">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <h3 id="sign">Add Product</h3> <br>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Product Name</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="inputEmail3" name="product_name">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="description">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Product No.</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="product_no">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">File Upload </label>
        <div class="col-sm-10">
          <input type="file" class="form-control" name="upload">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="price">
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-2 col-form-label">Current Stock</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="stock">
        </div>
        <br><br><br>
        <div class="mb-3">
          <button type="submit" class="btn btn-dark">Add</button>
        </div>
      </div>
       {{message}}
    </form>
  </section>
</body>

</html>

e_commerce/reseller/templates/resellertemplates/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/change.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
  <form class="div1" method="POST">
    {% csrf_token %}
      <h3 id="log">Change Password</h3>
      <div class="mb-3">
        <label  class="form-label">Current Password:</label>
        <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="curpass">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">New Password:</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="newpass">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Confirm:</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="conpass">
      </div>
      
      <button type="submit" class="btn btn-dark">Submit</button>
      <br/>
      {{message}}
    </form>
</body>
</html>

e_commerce/reseller/templates/resellertemplates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/reshome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
  <section class="header">
    <div class="div4">
      E-Commerce
    </div>
    <div class="div5">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link " href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Change Password</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">LogOut</a>
        </li>
      </ul>
    </div>
  </section> 
    <section class="div">
        <div class="div1">
            <a href="" id="v1"><p>Image</p></a>
            <a href="" id="v1"><p>Home</p></a>
            <a href="" id="v1"><p>Catelogue</p></a>
            <a href="{% url 'reseller:addpro'%}" id="v1"><p>Add Product</p></a>
            <a href="" id="v1"><p>Update Stock</p></a>
      
        </div>
        <div class="div2">  
          <div class="card" style="width: 18rem;">
            <img src="{% static 'images/1.jpg' %}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h5 class="card-title">Apple Watch Series 6</h5>
              <p class="card-text">₹40,900</p>
              <a href="#" class="btn btn-dark">Add Product</a>
            </div>
          </div>
          <div class="card" style="width: 18rem;">
            <img src="{% static 'images/2.jpg' %}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h5 class="card-title">Sony Headset</h5>
              <p class="card-text">₹2,500</p>
              <a href="#" class="btn btn-dark">Add Product</a>
            </div>
          </div>
          <div class="card" style="width: 18rem;">
            <img src="{% static 'images/3.jpeg' %}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h5 class="card-title">Canon 6D</h5>
              <p class="card-text"> <strike>₹40,000</strike>  ₹35,000</p> 
              <a href="#" class="btn btn-dark">Add Product</a>
            </div>
          </div>
          <div class="card" style="width: 18rem;">
            <img src="{% static 'images/4.webp' %}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h5 class="card-title">Toy Car</h5>
              <p class="card-text">₹1,500</p>
              <a href="#" class="btn btn-dark">Add Product</a>
            </div>
          </div>
          <div class="card" style="width: 18rem;">
            <img src="{% static 'images/5.jpg' %}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h5 class="card-title">Jacket</h5>
              <p class="card-text">₹3,500</p>
              <a href="#" class="btn btn-dark">Add Product</a>
            </div>
          </div>
          <div class="card" style="width: 18rem;">
            <img src="{% static 'images/6.jpg' %}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h5 class="card-title">Nike Shoes</h5>
              <p class="card-text">₹2,800</p>
              <a href="#" class="btn btn-dark">Add Product</a>
            </div>
          </div>
        </div>
      </section>    
</body>
</html>

e_commerce/reseller/templates/resellertemplates/product_catalouge.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/catalouge.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <section class="header">
        <div class="div1">
          E-Commerce
        </div>
        <div class="div2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link " href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LogOut</a>
            </li>
          </ul>
        </div>
      </section>

      <section class="div">
        <div class="div3"> 
            

          {% for product in products  %}
          <div class="card" style="width: 18rem;" >
           <img src="{{product.upload.url}}" class="card-img-top" alt="..." id="pic1">
            <div class="card-body">
              <h4 class="card-title">{{product.p_name}}</h4>
              <h6 class="card-title">{{product.description}}</h6>
              <p class="card-text">₹{{product.price}}</p>
              <div class="desc">Seller - {{product.seller.seller_name|title}}</div>
    
            </div>
          </div>
          {% endfor %}
        </div>
      </section> 

e_commerce/reseller/templates/resellertemplates/recent_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>recent orders</title>
    <link rel="stylesheet" href="{% static 'css/reorder.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
    <section class="header">
        <div class="div1">
          E-Commerce
        </div>
        <div class="div2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'reseller:procata' %}">Product catalogue</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:addpro' %}">Add product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:upstck' %}">Update Stock</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:chngpass' %}">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:recntordr' %}">Recent orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:ordrhstry' %}">History</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LogOut</a>
            </li>
          </ul>
        </div>
      </section>
        
        <div style="float: left;padding-left: 300px;color: white;padding-top: 100px;font-size: 20px;">
              
            <!-- <h1 style="color:white;"><i>MY ORDER</i></h1>
            <img src="{% static 'images/arrr.png' %}" alt="" height="125px" style="padding-left: 50px;"> -->
              <div>
                <table class="table table-dark table-striped" style="color:white;width: 1000px;font-size: 20px;border: 20rem;">
                  <thead>
                    <tr >
                      <th scope="col">product Number</th>
                      <th scope="col">PRODUCT NAME</th>
                      <th scope="col">DISCRIPTION</th>
                      <th scope="col">QUANTITY</th>
                      <th scope="col">PRICE</th>
                      <th scope="col">Date</th>
                      <th scope="col">ORDER STATUS</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
              
                   
                  </tbody>
                </table>
             
                 </div>

            </div>
     </div>
</body>
</html>

e_commerce/reseller/templates/resellertemplates/update_stock.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update Stock</title>
    <link rel="stylesheet" href="{% static 'css/upstock.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
    <section class="header">
        <div class="div1">
          E-Commerce
        </div>
        <div class="div2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'reseller:procata' %}">Product catalogue</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:addpro' %}">Add product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:upstck' %}">Update Stock</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:chngpass' %}">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:recntordr' %}">Recent orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:ordrhstry' %}">History</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LogOut</a>
            </li>
          </ul>
        </div>
      </section>
        
        <div style="float: left;padding-left: 400px;color: white;padding-top: 100px;font-size: 20px;">
             <i><h2 style="color: red;">UPDATE STOCK</h2></i><br />
            <div>
                <label for="exampleFormControlInput2" class="form-label">Product Number :</label>
                <input type="text" class="form-control" id="exampleFormControlInput2" style="width: 500px;">
            </div> <br />
          <div>
            <label for="exampleFormControlInput2" class="form-label">Current Stock :</label>
            <input type="text" class="form-control" id="exampleFormControlInput2" style="width: 500px;">
          </div><br />
          <div>
            <label for="exampleFormControlInput3" class="form-label">New Stock :</label>
            <input type="text" class="form-control" id="exampleFormControlInput3" style="width: 500px;">
          </div>
          <br />
             <center>
              <a href=""><button type="button" class="btn btn-outline-light" style="width: 200px;">UPDATE STOCK</button></a>
            </center>
            </div>
     </div>
</body>
</html>