e_commerce/common/urls.py
from django.urls import path
from . import views

app_name="common"
urlpatterns=[
    path('customer_login',views.customer_login,name='custlo'),
    path('customer_reg',views.customer_reg,name='custreg'),
    path('',views.project_home1,name='prohome'),
    path('seller_login',views.seller_login,name='sellerlog'),
    path('seller_reg',views.seller_reg,name='sellerreg'),
    path('check_email',views.check_email,name='check_email'),
]    

e_commerce/customer/urls.py
from django.urls import path
from . import views

app_name="customer"
urlpatterns=[
    path('home',views.home,name='cushome'),
    path('product_details/<int:pid>',views.product_details,name='prodetails'),

    path('my_cart',views.my_cart,name='mycart'),
    path('delete/<int:id>',views.delete_cart,name='del_cart'),

    path('my_order',views.my_cart,name='myorder'),
    path('change_password',views.change_password,name='chngpass'),
    path('profile',views.profile,name='profile'),

    path('logout',views.logout,name='logout'),
    
]    

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('reseller/', include('reseller.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('student/', include('restapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

e_commerce/customer/models.py
from django.db import models
from common.models import Customer
from reseller.models import Product

# Create your models here.

class cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    Product = models.ForeignKey(Product, on_delete = models.CASCADE)

e_commerce/customer/views.py
from django.shortcuts import render,redirect
from  reseller.models import Product
from . models import cart
from common.models import Customer
from .decorator import auth_customer

# Create your views here.

@auth_customer
def home(request):
    # if 'customer' in request.session:
        products = Product.objects.all() # select * from product
        # products = [
        #  {
        #    seller:2 
        #    product_name : 'laptop'
        #     -------- 
        #  },
        #  
        #    {
        #    seller:2 
        #    product_name : 'bag'
        #     -------- 
        #   }
        # ]
        return render(request, 'customertemplates/home.html', {'product_list': products})
    # else:
    #     return redirect('common:custlo')    

@auth_customer
def product_details(request,pid):
    msg = ''
    product_data = Product.objects.get(id = pid)  # fetching single data from table
    if request.method == 'POST':
        product_id = request.POST['pid']

        item_exist = cart.objects.filter(Product_id = product_id, customer_id = request.session['customer']).exists()
        if not item_exist: # if item_exist == false

            cart_item = cart(Product_id = product_id, customer_id = request.session['customer'])
            cart_item.save()
            return redirect('customer:mycart')
        else :
            msg = 'Item Already In Cart'    

    return render(request, 'customertemplates/product_details.html', {'product': product_data, 'message':msg})

@auth_customer
def my_cart(request):
    cart_details = cart.objects.filter(customer = request.session['customer'])

    return render(request, 'customertemplates/my_cart.html', {'cart': cart_details})

def my_order(request):
    return render(request, 'customertemplates/my_order.html')

@auth_customer
def change_password(request):
    msg = ''
    if request.method == 'POST':
        customer = Customer.objects.get(id = request.session['customer'])

        current_pass = request.POST['curpass']
        new_pass = request.POST['newpass']
        confirm_pass = request.POST['conpass']

        if customer.password == current_pass:

            if new_pass == confirm_pass:
                customer.password = new_pass
                customer.save()
                msg = 'Password Change Successfully'
            else:
                msg = 'Password Doesnot Match' 

        else:
            msg = 'Incorrect Password'          


    return render(request, 'customertemplates/change_password.html',{'message':msg})

def profile(request):
    return render(request, 'customertemplates/profile.html')


def delete_cart(request,id):

    cart_item = cart.objects.get(Product = id, customer = request.session['customer'])

    cart_item.delete()

    return redirect('customer:mycart')


def logout(request):

    del request.session['customer']   # delete session key
    request.session.flush()   # delete data from django session table
    return redirect('common:prohome')

e_commerce/customer/templates/customertemplates/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/cuschange.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
    <form class="div1" method="POST">
      {% csrf_token %}
        <h3 id="log">Change Password</h3>
        <div class="mb-3">
          <label  class="form-label">Current Password:</label>
          <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="curpass">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">New Password:</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="newpass">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Confirm:</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="conpass">
        </div>
        
        <button type="submit" class="btn btn-dark">Submit</button>
        <br/>
        {{message}}
      </form>

</body>
</html>

e_commerce/customer/templates/customertemplates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/custhome.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
  <section class="header">
    <div class="div1">
      E-Commerce
    </div>
    <div class="div2">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link " href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Change Password</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customer:logout' %}">LogOut</a>
        </li>
      </ul>
    </div>
  </section>
  <div id="hr"><hr></div>
  <section class="div">
    <div class="div3">  

      {% for product in product_list%}
      <div class="card" style="width: 18rem;">
       <img src="{{product.upload.url}}" class="card-img-top" alt="..." id="pic1">
        <div class="card-body">
          <h4 class="card-title">{{product.p_name}}</h4>
          <h6 class="card-title">{{product.description}}</h6>
          <p class="card-text">₹{{product.price}}</p>
          <a href="{% url 'customer:prodetails' product.id %}" class="btn btn-dark">view</a> <br><br>
          <div class="desc">Seller - {{product.seller.seller_name|title}}</div>

        </div>
      </div>
       {% endfor %}
    </div>
  </section>  
  <br/> <br/>
</body>
</html>

e_commerce/customer/templates/customertemplates/my_cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/prodetails.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <section class="header">
        <div class="div1">
          E-Commerce
        </div>
        <div class="div2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link " href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:logout' %}">LogOut</a>
            </li>
          </ul>
        </div>
      </section>
      <div id="hr"><hr></div>
     <section class="div">

    <section class="div">
        <table class="table table-dark table-striprd text-center">
          <tr>
            <th>SI.NO</th>
            <th>Product Name</th>
            <th>Description</th>
            <th>Product Number</th>
            <th>Product Image</th>
            <th>Total Price</th>
            <th></th>
        </tr>
          {% for details in cart  %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{details.Product.p_name}}</td>
                <td>{{details.Product.description}}</td>
                <td>{{details.Product.p_no}}</td>
                <td><img src="{{details.Product.upload.url}}" class="card-img-top" alt="..." style="width: 150px; height: 150px;"></td>
                <td>{{details.Product.price}}</td>
                <td> <a href="{% url 'customer:del_cart' details.id %}" style="text-decoration: none;">Delete</a> </td>
            </tr>
          {% endfor %}  
        </table>
    </section>    
    
</body>
</html>

e_commerce/customer/templates/customertemplates/product_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/prodetails.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <section class="header">
        <div class="div1">
          E-Commerce
        </div>
        <div class="div2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link " href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LogOut</a>
            </li>
          </ul>
        </div>
      </section>
      <div id="hr"><hr></div>
     <section class="div">

        <section class="div">
            <div class="div3">  
        
              <div class="card" style="width: 18rem;">
               <img src="{{product.upload.url}}" class="card-img-top" alt="..." id="pic1">
                <div class="card-body">
                  <form action="" method="POST">
                    {% csrf_token %}
                  <input type="hidden" value="{{product.id}}" name="pid">  
                  <h4 class="card-title">{{product.p_name|upper}}</h4>
                  <h6 class="card-title">{{product.description}}</h6>
                  <p class="card-text">₹{{product.price}}</p>
                  <button type="submit" class="btn btn-dark">Add To Cart</button> <br><br>
                  <div class="desc">Seller - {{product.seller.seller_name|title}}</div>
                </div>
                {{message}}
              </form>
              </div>
            </div>
          </section>    
    
</body>
</html>

e_commerce/customer/templates/customertemplates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/custprofile.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
    <section class="header">
        <div class="div1">
          E-Commerce
        </div>
        <div class="div2">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'customer:cushome' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LogOut</a>
            </li>
          </ul>
        </div>
      </section>
    <div id="hr"><hr></div>  
      
    <section class="div3">
      <h4>Profile Details</h4> 
      <hr> 
      <div class="div4">
       <div class="box1">
         <div>Full Name</div>
         <div> Mobile Number</div>
         <div>Email ID</div>
         <div>Gender</div>
         <div>Date Of Birth</div>
         <div>Location</div>
       </div>  
      <div class="box2">
        <div>Murshid Vp</div>
        <div>9605381393</div>
        <div>Murshid9873@gmail.com</div>
        <div>Male</div>
        <div>01/01/1999</div>
        <div>calicut</div>
       </div>
      </div>
      <div class="div5"><button type="button" class="btn btn-primary btn-sm">Edit</button></div> 
    </section>
</body>
</html>